name: epub_editor
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/abluescarab/dart-epub-editor
issue_tracker: https://github.com/abluescarab/dart-epub-editor/issues
# TODO: remove build number after finishing
version: 1.2.0+14

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  archive: ^3.1.6
  quiver: ^3.0.1+1
  path: ^1.8.1
  xml: ^6.0.1
  image: ^4.1.7
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.7
